homework_09/games/urls.py
from django.urls import path
from games import views

app_name = 'games'

urlpatterns = [
    path('', views.game_view, name='index'),
    path('list/', views.GameListView.as_view(), name='list'),
    path('game/<int:pk>/', views.GameDetailView.as_view(), name='detail'),
    path('create/', views.GameCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.GameUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.GameDeleteView.as_view(), name='delete'),

    path('rent_list/', views.RentListView.as_view(), name='rent'),
]

homework_09/rent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('users/', include('users.urls')),
    path('', include('games.urls')),
    path('admin/', admin.site.urls),

]

homework_09/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('login/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    ]

homework_09/games/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class StatusGame(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class AgeGame(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Game(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    status = models.ForeignKey(StatusGame, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    min_players = models.IntegerField()
    max_players = models.IntegerField()
    age_group = models.ForeignKey(AgeGame, on_delete=models.CASCADE)
    price = models.IntegerField()

    def __str__(self):
        return f'{self.name} ({self.age_group}) - {self.price} rub'


class RentGame(models.Model):
    game = models.ManyToManyField(Game)
    date_start = models.DateField()
    date_end = models.DateField()
    cost = models.IntegerField()

    def __str__(self):
        return f'{self.game} - {self.date_start} - {self.date_end}'

homework_09/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class AppUser(AbstractUser):
    name = models.CharField(max_length=100, null=False)
    phone = models.CharField(max_length=100, null=True)
    telegram = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)

homework_09/games/forms.py
from django import forms
from .models import Game,RentGame

class GameForm(forms.ModelForm):
    name = forms.CharField(
        label='Name',
        initial='New Game',
        widget=forms.TextInput(
            attrs={'placeholder': 'Enter Game Name',
                   'class': 'form-control'}
            )
    )
    class Meta:
        model = Game
        fields = '__all__'


class RentForm(forms.ModelForm):
    name = forms.CharField(
        label='Rent',
        initial='Rent Game',
        widget=forms.TextInput(
            attrs={'placeholder': 'Enter Game Name',
                   'class': 'form-control'}
            )
    )
    rent = forms.ModelMultipleChoiceField(
        queryset = Game.objects.all(),
        required = False,
        widget = forms.CheckboxSelectMultiple(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = RentGame
        fields = '__all__'

homework_09/users/forms.py
from django.contrib.auth.forms import UserCreationForm


from .models import AppUser

class RegisretForm(UserCreationForm):
    class Meta:
        model = AppUser
        fields = ('username', 'name','phone', 'telegram', 'address', 'password1', 'password2')

homework_09/games/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin,PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (ListView,
                                  DetailView, CreateView, UpdateView, DeleteView)
from games.models import Game,RentGame
from games.forms import GameForm



def game_view(request):
    model = Game.objects.all()
    return render(request, 'games/game_list.html', {'object_list': model})

class GameListView(ListView):
    model = Game


class GameDetailView(DetailView):
    model = Game

class GameCreateView(CreateView):
    model = Game
    form_class = GameForm
    success_url = reverse_lazy('games:list')

class GameUpdateView(UpdateView):
    model = Game
    fields = '__all__'
    success_url = reverse_lazy('games:list')

class GameDeleteView(DeleteView):
    model = Game
    success_url = reverse_lazy('games:list')
    permission_required = 'games.delete_game'

class RentListView(ListView):
    model = RentGame


class RentDetailView(DetailView):
    model = RentGame

homework_09/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from .models import AppUser
from .forms import RegisretForm

# Create your views here.
class AuthLoginView(LoginView):
    template_name = 'users/login.html'
    success_url = '/'


class RegisterView(CreateView):
    model = AppUser
    form_class = RegisretForm
    template_name = 'users/register.html'
    success_url = '/'

class ProfileView(DetailView):
    model = AppUser
    template_name = 'users/profile.html'

homework_09/games/templates/games/game_confirm_delete.html
{% block main %}
    Подтвердите удаление
    <form method="post">
        {% csrf_token %}
        <button type="submit">Да</button>
    </form>
{% endblock %}

homework_09/games/templates/games/game_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ game.name }}
{% endblock %}


{% block main %}
        <div class="row">
            <div class="col">
                <div class="card mb-3" style="max-width: 600px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-end"> {{ game.age_group }} </p>
                                <h5 class="card-title">{{ game.name }}</h5>
                                    <p class="card-text"><small class="text-muted">{{ game.category }}</small></p>
                                    <p class="card-text">{{ game.description }}</p>

                                    <p class="card-text"><small class="text-muted">Игроков: {{ game.min_players }} - {{ game.max_players }}</small></p>
                                    <p class="card-text">{{ game.status }}</p>
                                    <p class="card-text">{{ game.price }}₽/час</p>
                                <div class="btn-group">
                                    <a href="{% url 'games:list' %}">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

homework_09/games/templates/games/game_form.html
{% extends 'base.html' %}

{% block title %}
    New Game
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="form" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

homework_09/games/templates/games/game_list.html
{% extends 'base.html' %}

{% block title %}
    All Games
{% endblock %}

{% block main %}

        <div class="row">
        {% for game in object_list %}
            <div class="col-lg-4 mt-3 col-md-6 mt-3 row-sm">
                <div class="card mb-3" style="max-width: 600px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ game.name }}</h5>
                                <p class="card-text">{{ game.category }}</p>
                                <p class="card-text"><small class="text-muted">Игроков: {{ game.min_players }} - {{ game.max_players }}</small></p>
                                <div class="btn-group-md-3 btn-group-sm">
                                    <a href="{% url 'games:detail' pk=game.pk %}" class="btn btn-link">
                                        Подробнее
                                    </a>
                                    {% if user.is_staff and user.is_authenticated %}
                                    <a href="{% url 'games:update' pk=game.pk %}" class="btn btn-link">
                                        Редактировать
                                    </a>
                                    <a href="{% url 'games:delete' pk=game.pk %}" class="btn btn-link">
                                        Удалить
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
        </div>
{% endblock %}

{% block section %}
    <div class="container">
        {% include "components/sections.html" %}
    </div>
{% endblock %}

homework_09/games/templates/games/rent_form.html
{% extends 'base.html' %}

{% block title %}
    Rent Game
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="form" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

homework_09/games/templates/games/rent_list.html
{% extends 'base.html' %}

{% block title %}
    All Games
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
        {% for game in object_list %}
            <div class="col-lg-3 mt-3 col-md-6 mt-3 row-sm">
                <div class="card mb-3" style="max-width: 600px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ game.name }}</h5>
                                <p class="card-text">{{ game.category }}</p>
                                <p class="card-text"><small class="text-muted">Игроков: {{ game.min_players }} - {{ game.max_players }}</small></p>
                                <div class="btn-group-md-3 btn-group-sm">
                                    <a href="{% url 'games:detail' pk=game.pk %}" class="btn btn-link">
                                        Подробнее
                                    </a>
                                    <a href="{% url 'games:update' pk=game.pk %}" class="btn btn-link">
                                        Редактировать
                                    </a>
                                    <a href="{% url 'games:delete' pk=game.pk %}" class="btn btn-link">
                                        Удалить
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

homework_09/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            GameShop
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include "components/navbar.html" %}

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-0">

            </div>
            <div class="col-md-8 col-sm-12">
                {% block main %}

                {% endblock %}
            </div>
             <div class="col-md-2 col-sm-0">
                {% block section %}

                {% endblock %}
            </div>
        </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

homework_09/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">YouGame</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'games:list' %}">Все игры</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Бронирование</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Акции</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            О нас
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Контакты</a></li>
            <li><a class="dropdown-item" href="#">Условия аренды и покупки</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Обратная связь</a></li>
          </ul>
        </li>
      </ul>
        <span class="navbar-text">
            {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'users:profile' pk=user.pk %}">{{user.name}}</a>
            {% else %}
                <a class="dropdown-item" href="{% url 'users:login' %}">Войти</a>
            {% endif %}
        </span>
      </div>
  </div>
</nav>

homework_09/templates/components/sections.html
<div class="row">
    <div class="col mt-3">
        <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col">
                            <div class="card-body">
                                <p class="nav-link">Разделы</p>
                                    <a class="nav-link" href="{% url 'games:list' %}">Все игры</a>

                                    <a class="nav-link" href="{% url 'games:list' %}">Популярное</a>

                                    <a class="nav-link" href="{% url 'games:list' %}">Доступно сейчас</a>

                            </div>
                        </div>
                    </div>
        </div>
    </div>
</div>

homework_09/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}
    Вход в профиль
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="form" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                    <button class="btn btn-primary" type="submit">Войти</button>
                    <a class="btn btn-primary" type="submit" href="{% url 'users:register' %}">Зарегестрироваться</a>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

homework_09/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    Профиль, {{ user.name }}
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card mb-3" style="max-width: 600px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-end"> {{ user.name }} </p>
                                    <h5 class="card-title">{{ user.username }}</h5>
                                    <p class="card-text">{{ user.address }}</p>
                                    <p class="card-text">{{ user.phone }}</p>
                                    <p class="card-text">{{ user.telegram }}</p>
                                    <div class="btn-group">
                                        <form method="post" action="{% url 'users:logout' %}">
                                              {% csrf_token %}
                                              <button class="btn" type="submit">Выход</button>
                                          </form>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

homework_09/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="form" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}

                    <button class="btn btn-primary" type="submit">Зарегестрироваться</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}