homework_08/games/urls.py
from django.urls import path
from games import views

app_name = 'games'

urlpatterns = [
    path('', views.game_view, name='index'),
    path('games/', views.GameListView.as_view(), name='list'),
    path('games/<int:pk>/', views.GameDetailView.as_view(), name='detail'),
]

homework_08/games/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class StatusGame(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class AgeGame(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Game(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    status = models.ForeignKey(StatusGame, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    min_players = models.IntegerField()
    max_players = models.IntegerField()
    age_group = models.ForeignKey(AgeGame, on_delete=models.CASCADE)
    price = models.IntegerField()

    def __str__(self):
        return f'{self.name} ({self.age_group}) - {self.price} rub'


# class RentGame(models.Model):
#     game = models.ForeignKey(Game, on_delete=models.CASCADE)
#     date_start = models.DateField()
#     date_end = models.DateField()
#     cost = models.IntegerField()
#
#     def __str__(self):
#         return f'{self.game} - {self.date_start} - {self.date_end}'

homework_08/games/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (ListView,
                                  DetailView)
from games.models import Game


def game_view(request):
    model = Game.objects.all()
    return render(request, 'games/game_list.html', {'object_list': model})

class GameListView(ListView):
    model = Game


class GameDetailView(DetailView):
    model = Game

homework_08/games/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            GameShop
        {% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <div class="row">
        {% block main %}

        {% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

homework_08/games/templates/games/game_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ game.name }}
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card mb-3" style="max-width: 600px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body">
                                <p class="card-end"> {{ game.age_group }} </p>
                                <h5 class="card-title">{{ game.name }}</h5>
                                    <p class="card-text"><small class="text-muted">{{ game.category }}</small></p>
                                    <p class="card-text">{{ game.description }}</p>

                                    <p class="card-text"><small class="text-muted">Игроков: {{ game.min_players }} - {{ game.max_players }}</small></p>
                                    <p class="card-text">{{ game.status }}</p>
                                    <p class="card-text">{{ game.price }}₽/час</p>
                                <div class="btn-group">
                                    <a href="{% url 'games:list' %}">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

homework_08/games/templates/games/game_list.html
{% extends 'base.html' %}

{% block title %}
    All Games
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
        {% for game in object_list %}
            <div class="col-lg-3 mt-3 col-md-6 mt-3 row-sm">
                <div class="card mb-3" style="max-width: 600px;">
                    <div class="row g-0">
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ game.name }}</h5>
                                <p class="card-text">{{ game.category }}</p>
                                <p class="card-text"><small class="text-muted">Игроков: {{ game.min_players }} - {{ game.max_players }}</small></p>
                                <div class="btn-group">
                                    <a href="{% url 'games:detail' pk=game.pk %}">
                                        Подробнее
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}